const displayError = (a, b, data) => {
    console.log("showMessage arrow function called");
    return a + b;
    return x * y;
    alert('Action completed!');
};